spring:
  profiles: 
    default: dev
  basic:
    enabled: false

  # Send distributed traces to zipkin server (using Eureka to find the server)
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: http://zipkin-service/

#Environment
environment: DEV
# Configure this Discovery Server
# tag::configuration-eureka[]
eureka:
  instance:
    metadata-map:
      user.name: "avatar"         #These two are needed so that the server
      user.password: "eureka" #can access the protected client endpoints
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
      
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://avatar:eureka@localhost:1100}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS
# end::configuration-eureka[]

# HTTP (Tomcat) port
server:
  port: 9090

# zuul config
zuul:
  retryable: true
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
      master-service:
        path: /api/**
        serviceId: master-service
      authorization-service:
        path: /api/**
        serviceId: authorization-service
      product-service:
        path: /api/**
        serviceId: product-service
      transaction-service:
        path: /api/**
        serviceId: transaction-service
      notification-service:
        path: /api/**
        serviceId: notification-service

# logging
logging:
  file: logs/application-debug.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: DEBUG
    org.hibernate: WARN
    com.kirana: DEBUG

ribbon:
  retryable: true
  ConnectTimeout: 3000
  ReadTimeout: 60000
feign:
  histrix:
    enabled: false

hystrix:
  command:
    choose:
      default:
        execution:
          timeout:
            enabled: false